name: auto-clang-format
on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        ref: ${{ github.head_ref }}
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './lib/inja ./lib/url-matcher ./tests/Catch2'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 12
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@clang
        message: ':art: Committing clang-format changes'
        ref: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}